title: Elacalle's developer blog
author: Ernesto Lacalle
# email: email@domain.com
description: > # this means to ignore newlines until "show_exerpts:"
  Blog about my advetures as RoR, Ruby and Web development in brief.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Ernesto Lacalle
  tagline: Ruby and RoR Developer.
  date_format: "%b %-d, %Y"
  style: red
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    # twitter: thelehhman
    github: edlahaba
    linkedIn: in/ernesto-de-la-haba-lacalle/
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture
remote_theme: thelehhman/texture
plugins:
  - jekyll-feed
  - jekyll-seo-tag
